services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  urlresume:
    build:
      context: .
      dockerfile: Dockerfile
      target: final
    image: urlresume:latest
    env_file:
      - .env
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development
      - Redis__ConnectionString=redis:6379
      - Storage__Provider=DynamoDB
      - AWS__Region=${AWS__Region:-us-east-1}
      # AWS/DynamoDB (pass via .env)
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - DynamoDB__TableName=${DYNAMO_TABLE_NAME:-url-resume}
    ports:
      - "8080:8080"
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
